name: Follett -- NY Yacht Club Fireplaces
favicon: null
layout_spectrum: 0.27899582125246525
typography_spectrum: 0.3787134175654501
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#29120c'
    - '#dbaa7f'
    - '#b9926b'
    - '#825433'
    - '#fbd5a8'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.6024515156168491
purpose: []
